### ISSUE TITLE
Add HortusFox

### ISSUE THREAD

**Issue by danielbrendel** [sereneblue/awesome-oss#46]
Hi, this is a nice list!

Maybe you'd like to add HortusFox? It's a selfhosted FOSS that can be used to manage your indoor plants. It has quite a lot of features.

Contribution link: https://github.com/danielbrendel/hortusfox-web
Donation link: https://ko-fi.com/danielbrendel 

Kind regards

**Comment by sereneblue** [comment]
Hi Daniel,

Cool project, I've added it the readme.
