### ISSUE TITLE
FreeCAD as alternative for Creo Parametric, Catia, Fusion 360, Siemens NX,...

### ISSUE THREAD

**Issue by Torxal** [sereneblue/awesome-oss#7]
Hey, 

thanks for the nice list. Maybe you can add FreeCAD to the list. Its a free and open source parametric 3d paramatric modeler for use in mechanical engineering. It although supports Python and C++API development.  https://www.freecadweb.org/ 

FreeCad is a alternative for commercial programms like: Creo Parametric, Catia, Fusion 360, Siemens NX, ...

**Comment by sereneblue** [comment]
Thanks @Torxal. I've added FreeCAD to the list.
