### ISSUE TITLE
Add YouTubeDownloader by Tyrrrz

### ISSUE THREAD

**Issue by merlindoescode** [sereneblue/awesome-oss#9]
Hey,

first of all nice list/project you got here.

I have am opensource tool here: "https://github.com/Tyrrrz/YoutubeDownloader" but i am not sure if it is a right addition to this list. If it is a good additon then there is the need of a new group for it, I think.

**Comment by merlindoescode** [comment]
ok...

maybe i was just blind 😅 could it be that the correct list would be "Others" ?

**Comment by sereneblue** [comment]
@merlindoescode Thank you for contributing but that project doesn't quite fit in with the other tools you created a pull request for.
